services:
  postgres:
    image: postgres:latest
    environment:
    - POSTGRES_DB=tracing-log-service
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - "5433:5432"
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=my-app
    command:
      - --replSet
      - rs0
      - --bind_ip_all
    ports:
      - "27018:27017"
    healthcheck:
      test: test $$(mongosh --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]})}
        catch(e) {rs.status().ok}") -eq 1
      interval: 5s
      timeout: 5s
      retries: 10
