spring:
  profiles:
    active: mysql
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_DATABASE_URL:mongodb://localhost:27017/my-app}
  docker:
    compose:
      lifecycle-management: start_only
  messages:
    basename: i18n/messages
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
logging:
  level:
    root: info
    web: debug
    io.lifeberries.tracing_log_service: info
